name: Auto-Commit Every 5 Hours

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history

      - name: Update repo
        run: |
          # Reset to latest remote changes
          git fetch origin
          git reset --hard origin/main  # Replace "main" with your branch name

          # Create commit
          echo "Auto-commit: $(date)" >> activity.log
          git add activity.log
          git config user.email "mufeez.qadri22@gmail.com"
          git config user.name "MufeezQadri-main"
          git commit -m "Auto-commit [skip ci]"

      - name: Force push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true  # Overwrite remote history
          branch: main  # Must match your branch name
